name: Build and Publish to Pages
on: [push]
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
      - uses: actions/checkout@v2
      - id: Build-Vue
        env:
          VITE_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
        uses: lewisdoesstuff/VuePagesAction@1.0.2
        with:
          username: 'hirotasoshu'
          reponame: 'bento-next'
          token: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
